# Generated by Django 4.2.4 on 2023-08-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laboratory",
            name="equipment_list",
            field=models.TextField(verbose_name=200),
        ),
        migrations.AlterField(
            model_name="schoolfacility",
            name="usage_purpose",
            field=models.TextField(max_length=200),
        ),
    ]
